"""Fetech public Python API."""

from fetech.adapters.cache import ArchivedSnapshot, SnapshotConnector
from fetech.adapters.documents import (
    GitLFSResolvedObject,
    GitLFSResolver,
    GitLFSResolveRequest,
    PDFOCRPage,
    PDFOCRProvider,
)
from fetech.adapters.media import MediaAdapter, TranscriptProvider, YouTubeMetadataProvider
from fetech.auth import (
    CredentialMaterial,
    CredentialNotFoundError,
    CredentialProvider,
    CredentialProviderError,
    CredentialProviderUnavailableError,
    InMemoryCredentialProvider,
    RefreshableCredentialProvider,
)
from fetech.auth_flows import (
    FormSubmission,
    FormSubmissionApproval,
    FormSubmissionProvider,
    InMemoryFormSubmissionProvider,
    InMemorySessionProvider,
    NullSessionProvider,
    OriginScopedSession,
    PrivateWorkspaceTarget,
    SessionProvider,
    extract_csrf_token,
)
from fetech.client import FetechClient
from fetech.context import ContextBroker, ContextBudget, classify_context_needs
from fetech.contracts import contract_manifest
from fetech.errors import (
    FetechValidationError,
    public_validation_error,
    validate_context_request,
    validate_fetch_request,
    validate_uuid,
)
from fetech.failures import failure_catalogue
from fetech.logic.models import ReasoningQuery, ReasoningResult
from fetech.models import (
    Artifact,
    CapabilityOutcome,
    CapabilityOutcomeStatus,
    ContextBundle,
    ContextNeed,
    ContextProviderReport,
    ContextProviderStatus,
    ContextSource,
    ContextTokenUsage,
    ContractDescriptor,
    ContractManifest,
    CrawlReport,
    DiscoveredTarget,
    FailureCatalogue,
    FailureCodeDescriptor,
    FetchPlan,
    FetchRequest,
    FetchResult,
    PublicError,
    PublicErrorCode,
    PublicErrorDescriptor,
    ResourceBudget,
    ResultStatus,
    ResultStatusDescriptor,
    ValidationIssue,
)
from fetech.version import __version__
from fetech.wayback import WaybackSnapshotConnector

__all__ = [
    "ArchivedSnapshot",
    "Artifact",
    "CapabilityOutcome",
    "CapabilityOutcomeStatus",
    "ContextBroker",
    "ContextBudget",
    "ContextBundle",
    "ContextNeed",
    "ContextProviderReport",
    "ContextProviderStatus",
    "ContextSource",
    "ContextTokenUsage",
    "ContractDescriptor",
    "ContractManifest",
    "CrawlReport",
    "CredentialMaterial",
    "CredentialNotFoundError",
    "CredentialProvider",
    "CredentialProviderError",
    "CredentialProviderUnavailableError",
    "DiscoveredTarget",
    "FailureCatalogue",
    "FailureCodeDescriptor",
    "FetchPlan",
    "FetchRequest",
    "FetchResult",
    "FetechClient",
    "FetechValidationError",
    "FormSubmission",
    "FormSubmissionApproval",
    "FormSubmissionProvider",
    "GitLFSResolveRequest",
    "GitLFSResolvedObject",
    "GitLFSResolver",
    "InMemoryCredentialProvider",
    "InMemoryFormSubmissionProvider",
    "InMemorySessionProvider",
    "MediaAdapter",
    "NullSessionProvider",
    "OriginScopedSession",
    "PDFOCRPage",
    "PDFOCRProvider",
    "PrivateWorkspaceTarget",
    "PublicError",
    "PublicErrorCode",
    "PublicErrorDescriptor",
    "ReasoningQuery",
    "ReasoningResult",
    "RefreshableCredentialProvider",
    "ResourceBudget",
    "ResultStatus",
    "ResultStatusDescriptor",
    "SessionProvider",
    "SnapshotConnector",
    "TranscriptProvider",
    "ValidationIssue",
    "WaybackSnapshotConnector",
    "YouTubeMetadataProvider",
    "__version__",
    "classify_context_needs",
    "contract_manifest",
    "extract_csrf_token",
    "failure_catalogue",
    "public_validation_error",
    "validate_context_request",
    "validate_fetch_request",
    "validate_uuid",
]
